# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

correlationmatrixcpp <- function(G1, tau = 0, tol = 1e-6) {
    .Call('_npfixedcomp2_correlationmatrixcpp', PACKAGE = 'npfixedcomp2', G1, tau, tol)
}

pnnlssum <- function(A, b, sum) {
    .Call('_npfixedcomp2_pnnlssum', PACKAGE = 'npfixedcomp2', A, b, sum)
}

pnnqp <- function(q, p, sum) {
    .Call('_npfixedcomp2_pnnqp', PACKAGE = 'npfixedcomp2', q, p, sum)
}

#' The density and the distribution function of non-parametric normal distribution
#'
#' One-dimensional case: \code{dnpnorm} gives the density, \code{pnpnorm} gives the distribution function.
#'
#' Multi-dimensional case: \code{dnpnormND} gives the density.
#'
#' @title non-parametric normal distribution
#' @param x vector of observations, vector of quantiles for 1D and a m-by-n matrix for n-dimensional case. 
#' @param mu0 the vector of support points for 1D and a k-by-n matrix for n-dimensional case.
#' @param stdev standard deviation for 1D and covariance matrix for multi-dimensional case.
#' @param pi0 the vector of weights correponding to the support points
#' @param lt logical; if TRUE, the lower probability is computed
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npnorm
#' @export
dnpnorm <- function(x, mu0, pi0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dnpnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lg)
}

dnormarray_ <- function(x, mu0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dnormarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, lg)
}

#' @rdname npnorm
#' @export
pnpnorm <- function(x, mu0, pi0, stdev = 1, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pnpnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lt, lg)
}

pnormarray_ <- function(x, mu0, stdev = 1, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pnormarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, lt, lg)
}

#' The density and the distribution function of non-parametric one-parameter normal distribution
#'
#' \code{dnpnormc} gives the density
#'
#' @title non-parametric one-parameter normal distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param n number of observations (not the length of x)
#' @param pi0 the vector of weights correponding to the support points
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npnormc
#' @export
dnpnormc <- function(x, mu0, pi0, n, lg = FALSE) {
    .Call('_npfixedcomp2_dnpnormc', PACKAGE = 'npfixedcomp2', x, mu0, pi0, n, lg)
}

dnormcarray_ <- function(x, mu0, n, lg = FALSE) {
    .Call('_npfixedcomp2_dnormcarray_', PACKAGE = 'npfixedcomp2', x, mu0, n, lg)
}

#' The density and the distribution function of non-parametric t distribution
#'
#' \code{dnpt} gives the density, \code{pnpt} gives the distribution function.
#'
#' @title non-parametric t distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param df degree of freedom.
#' @param pi0 the vector of weights correponding to the support points
#' @param lt logical; if TRUE, the lower probability is computed
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npt
#' @export
dnpt <- function(x, mu0, pi0, df, lg = FALSE) {
    .Call('_npfixedcomp2_dnpt', PACKAGE = 'npfixedcomp2', x, mu0, pi0, df, lg)
}

dtarray_ <- function(x, mu0, df, lg = FALSE) {
    .Call('_npfixedcomp2_dtarray_', PACKAGE = 'npfixedcomp2', x, mu0, df, lg)
}

#' @rdname npt
#' @export
pnpt <- function(x, mu0, pi0, df, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pnpt', PACKAGE = 'npfixedcomp2', x, mu0, pi0, df, lt, lg)
}

ptarray_ <- function(x, mu0, df, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_ptarray_', PACKAGE = 'npfixedcomp2', x, mu0, df, lt, lg)
}

#' The density and the distribution function of non-parametric discrete normal distribution
#'
#' \code{dnpdiscnorm} gives the density and \code{pnpdiscnorm} gives the CDF.
#'
#' In this implementation, the support space is ..., -h, 0, h, ...
#'
#' @title non-parametric discrete normal distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param pi0 the vector of weights correponding to the support points
#' @param stdev standard deviation
#' @param h the bin width
#' @param lt logical; if TRUE, the result will be given in lower tail.
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npdiscnorm
#' @export
dnpdiscnorm <- function(x, mu0, pi0, stdev, h, lg = FALSE) {
    .Call('_npfixedcomp2_dnpdiscnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, h, lg)
}

ddiscnormarray_ <- function(x, mu0, stdev, h, lg = FALSE) {
    .Call('_npfixedcomp2_ddiscnormarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, h, lg)
}

#' @rdname npdiscnorm
#' @export
pnpdiscnorm <- function(x, mu0, pi0, stdev, h, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pnpdiscnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, h, lt, lg)
}

pdiscnormarray_ <- function(x, mu0, stdev, h, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pdiscnormarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, h, lt, lg)
}

#' The density and the distribution function of non-parametric poisson distribution
#'
#' \code{dnppois} gives the density, \code{pnppois} gives the distribution function.
#'
#' It is important to note that \code{pnppois} and its underlying function did not use
#' logspaceadd type implementation, the accuracy may be affected. 
#'
#' @title non-parametric normal distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param stdev structure parameter, passed but not referenced, for compatibility
#' @param pi0 the vector of weights correponding to the support points
#' @param lt logical; if TRUE, the lower probability is computed
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname nppois
#' @export
dnppois <- function(x, mu0, pi0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dnppois', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lg)
}

dpoisarray_ <- function(x, mu0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dpoisarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, lg)
}

#' @rdname nppois
#' @export
pnppois <- function(x, mu0, pi0, stdev = 1, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pnppois', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lt, lg)
}

ppoisarray_ <- function(x, mu0, stdev = 1, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_ppoisarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, lt, lg)
}

#' The density of non-parametric discrete non-central t distribution
#'
#' \code{dnpdisct} gives the density .
#'
#' In this implementation, the support space is ..., -h, 0, h, ...
#'
#' @title non-parametric discrete non-central t distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param pi0 the vector of weights correponding to the support points
#' @param df the degree of freedom
#' @param h the bin width
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npdisct
#' @export
dnpdisct <- function(x, mu0, pi0, df, h, lg = FALSE) {
    .Call('_npfixedcomp2_dnpdisct', PACKAGE = 'npfixedcomp2', x, mu0, pi0, df, h, lg)
}

ddisctarray_ <- function(x, mu0, df, h, lg = FALSE) {
    .Call('_npfixedcomp2_ddisctarray_', PACKAGE = 'npfixedcomp2', x, mu0, df, h, lg)
}

log1mexp_ <- function(x) {
    .Call('_npfixedcomp2_log1mexp_', PACKAGE = 'npfixedcomp2', x)
}

logspaceadd_ <- function(lx, ly) {
    .Call('_npfixedcomp2_logspaceadd_', PACKAGE = 'npfixedcomp2', lx, ly)
}

#' @rdname npnorm
#' @export
dnpnormND <- function(x, mu0, pi0, stdev, lg = FALSE) {
    .Call('_npfixedcomp2_dnpnormND', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lg)
}

dnormNDarray_ <- function(x, mu0, stdev, lg = FALSE) {
    .Call('_npfixedcomp2_dnormNDarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, lg)
}

colmix2D <- function(mu0, pi0, prec) {
    invisible(.Call('_npfixedcomp2_colmix2D', PACKAGE = 'npfixedcomp2', mu0, pi0, prec))
}

npnorm2Dll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnorm2Dll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

npnormad_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormad_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormad_ <- function(data, beta, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormad_', PACKAGE = 'npfixedcomp2', data, beta, val, initpt, initpr, gridpoints, tol, verbose)
}

gfnpnormad <- function(data, mu0fixed, pi0fixed, beta, mu0, pi0, gridpoints) {
    .Call('_npfixedcomp2_gfnpnormad', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, mu0, pi0, gridpoints)
}

npnormadw_ <- function(data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormadw_', PACKAGE = 'npfixedcomp2', data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormadw_ <- function(data, weights, beta, h, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormadw_', PACKAGE = 'npfixedcomp2', data, weights, beta, h, val, initpt, initpr, gridpoints, tol, verbose)
}

npnormcll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormcll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormcll_ <- function(data, beta, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormcll_', PACKAGE = 'npfixedcomp2', data, beta, val, initpt, initpr, gridpoints, tol, verbose)
}

npnormcvm_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormcvm_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormcvm_ <- function(data, beta, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormcvm_', PACKAGE = 'npfixedcomp2', data, beta, val, initpt, initpr, gridpoints, tol, verbose)
}

gfnpnormcvm <- function(data, mu0fixed, pi0fixed, beta, mu0, pi0, gridpoints) {
    .Call('_npfixedcomp2_gfnpnormcvm', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, mu0, pi0, gridpoints)
}

npnormcvmw_ <- function(data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormcvmw_', PACKAGE = 'npfixedcomp2', data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormcvmw_ <- function(data, weights, beta, h, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormcvmw_', PACKAGE = 'npfixedcomp2', data, weights, beta, h, val, initpt, initpr, gridpoints, tol, verbose)
}

npnormll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormll_ <- function(data, beta, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormll_', PACKAGE = 'npfixedcomp2', data, beta, val, initpt, initpr, gridpoints, tol, verbose)
}

npnormllw_ <- function(data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_npnormllw_', PACKAGE = 'npfixedcomp2', data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0npnormllw_ <- function(data, weights, beta, h, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0npnormllw_', PACKAGE = 'npfixedcomp2', data, weights, beta, h, val, initpt, initpr, gridpoints, tol, verbose)
}

nppoisll_ <- function(data, weights, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_nppoisll_', PACKAGE = 'npfixedcomp2', data, weights, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0nppoisll_ <- function(data, weights, beta, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0nppoisll_', PACKAGE = 'npfixedcomp2', data, weights, beta, val, initpt, initpr, gridpoints, tol, verbose)
}

nptll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_nptll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0nptll_ <- function(data, beta, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0nptll_', PACKAGE = 'npfixedcomp2', data, beta, val, initpt, initpr, gridpoints, tol, verbose)
}

nptllw_ <- function(data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = 0L) {
    .Call('_npfixedcomp2_nptllw_', PACKAGE = 'npfixedcomp2', data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol, maxit, verbose)
}

estpi0nptllw_ <- function(data, weights, beta, h, val, initpt, initpr, gridpoints, tol = 1e-6, verbose = 0L) {
    .Call('_npfixedcomp2_estpi0nptllw_', PACKAGE = 'npfixedcomp2', data, weights, beta, h, val, initpt, initpr, gridpoints, tol, verbose)
}

