# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
pnnlssum <- function(A, b, sum) {
    .Call('_npfixedcomp2_pnnlssum', PACKAGE = 'npfixedcomp2', A, b, sum)
}

#' @export
pnnqp <- function(q, p, sum) {
    .Call('_npfixedcomp2_pnnqp', PACKAGE = 'npfixedcomp2', q, p, sum)
}

#' @export
diff <- function(x) {
    .Call('_npfixedcomp2_diff', PACKAGE = 'npfixedcomp2', x)
}

#' @export
dnpnorm <- function(x, mu0, pi0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dnpnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lg)
}

#' @export
npnormll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_npnormll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

