# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pnnlssum <- function(A, b, sum) {
    .Call('_npfixedcomp2_pnnlssum', PACKAGE = 'npfixedcomp2', A, b, sum)
}

pnnqp <- function(q, p, sum) {
    .Call('_npfixedcomp2_pnnqp', PACKAGE = 'npfixedcomp2', q, p, sum)
}

#' The density and the distribution function of non-parametric normal distribution
#'
#' \code{dnpnorm} gives the density, \code{pnpnorm} gives the distribution function.
#'
#' @title non-parametric normal distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param stdev standard deviation.
#' @param pi0 the vector of weights correponding to the support points
#' @param lt logical; if TRUE, the lower probability is computed
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npnorm
#' @export
dnpnorm <- function(x, mu0, pi0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dnpnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lg)
}

dnormarray_ <- function(x, mu0, stdev = 1, lg = FALSE) {
    .Call('_npfixedcomp2_dnormarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, lg)
}

#' @rdname npnorm
#' @export
pnpnorm <- function(x, mu0, pi0, stdev = 1, lt = TRUE, lg = FALSE) {
    .Call('_npfixedcomp2_pnpnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, lt, lg)
}

#' The density and the distribution function of non-parametric one-parameter normal distribution
#'
#' \code{dnpnormc} gives the density
#'
#' @title non-parametric one-parameter normal distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param n number of observations (not the length of x)
#' @param pi0 the vector of weights correponding to the support points
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npnormc
#' @export
dnpnormc <- function(x, mu0, pi0, n, lg = FALSE) {
    .Call('_npfixedcomp2_dnpnormc', PACKAGE = 'npfixedcomp2', x, mu0, pi0, n, lg)
}

dnormcarray_ <- function(x, mu0, n, lg = FALSE) {
    .Call('_npfixedcomp2_dnormcarray_', PACKAGE = 'npfixedcomp2', x, mu0, n, lg)
}

#' The density and the distribution function of non-parametric t distribution
#'
#' \code{dnpnorm} gives the density.
#'
#' @title non-parametric t distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param df degree of freedom.
#' @param pi0 the vector of weights correponding to the support points
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npt
#' @export
dnpt <- function(x, mu0, pi0, df, lg = FALSE) {
    .Call('_npfixedcomp2_dnpt', PACKAGE = 'npfixedcomp2', x, mu0, pi0, df, lg)
}

dtarray_ <- function(x, mu0, df, lg = FALSE) {
    .Call('_npfixedcomp2_dtarray_', PACKAGE = 'npfixedcomp2', x, mu0, df, lg)
}

#' The density and the distribution function of non-parametric discrete normal distribution
#'
#' \code{dnpdiscnorm} gives the density.
#'
#' @title non-parametric discrete normal distribution
#' @param x vector of observations, vector of quantiles
#' @param mu0 the vector of support points
#' @param pi0 the vector of weights correponding to the support points
#' @param stdev standard deviation
#' @param h the bin width
#' @param lg logical; if TRUE, the result will be given in log scale.
#' @rdname npdiscnorm
#' @export
dnpdiscnorm <- function(x, mu0, pi0, stdev, h, lg = FALSE) {
    .Call('_npfixedcomp2_dnpdiscnorm', PACKAGE = 'npfixedcomp2', x, mu0, pi0, stdev, h, lg)
}

ddiscnormarray_ <- function(x, mu0, stdev, h, lg = FALSE) {
    .Call('_npfixedcomp2_ddiscnormarray_', PACKAGE = 'npfixedcomp2', x, mu0, stdev, h, lg)
}

npnormad_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_npnormad_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

npnormcll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_npnormcll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

npnormcvm_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_npnormcvm_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

npnormll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_npnormll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

npnormllw_ <- function(data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_npnormllw_', PACKAGE = 'npfixedcomp2', data, weights, mu0fixed, pi0fixed, beta, h, initpt, initpr, gridpoints, tol, maxit, verbose)
}

nptll_ <- function(data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol = 1e-6, maxit = 100L, verbose = FALSE) {
    .Call('_npfixedcomp2_nptll_', PACKAGE = 'npfixedcomp2', data, mu0fixed, pi0fixed, beta, initpt, initpr, gridpoints, tol, maxit, verbose)
}

